### ISSUE TITLE
Ask to create alternate file if missing

### ISSUE THREAD

**Issue by atipugin** [jasonrudolph/significant-other-vscode#2]
Hi @jasonrudolph 

Thanks for the extension! I always wanted something like this but was too lazy to build it on my own :) The only thing i'm missing is  ability to create alternate file if it doesn't exist. So instead of "No significant other found 😱" notification we can show dialog "No significant other found 😱 Create one? Yes/No".

Upd: just checked out the code and realized that extension doesn't really know which file to create, it only tries to find one of possible candidates.

**Comment by jasonrudolph** [comment]
> Upd: just checked out the code and realized that extension doesn't really know which file to create, it only tries to find one of possible candidates.

That's right. 

I can't think of a way for the extension to know exactly which file to create.

This could probably be solved by adding some configuration settings, but then we take on the complexity of dealing with configuration settings, and users deal with the burden of specifying those settings, which is [something I aspire to avoid](https://github.com/jasonrudolph/significant-other-vscode/commit/fd3c9d6a705f2f7c03ee0da5666026f8e2c137c5) for the reasons noted in https://github.com/jasonrudolph/significant-other-vscode/issues/3#issuecomment-1043705981.

With that in mind, I'm going to close this out. But if someone has an idea for how Significant Other could know which file is the exact right one to create, I'm open to exploring it. :-)

**Comment by atipugin** [comment]
Yes, we could use config files (something similar to vim-projectionist), but it would ruin the simplicity of extension. Anyway, again thanks for your work!
