### ISSUE TITLE
Configurable parts

### ISSUE THREAD

**Issue by fatfisz** [jasonrudolph/significant-other-vscode#3]
I thought someone mentioned it, and the closest issue I see is #1, but it's not quite that, so here I go:

How about making path parts configurable? I'm thinking that this could be useful when working with Storybook's stories, but then it doesn't seem to be sensible to support every possible project structure under the sun. Of course, a base of parts like test_, test., etc. is good, but this plugin could enable so much more with a little extra cost (unless it's hard to make plugins configurable, which I'm not knowledgeable about).

In any case, thanks for your work!

**Comment by jasonrudolph** [comment]
> How about making path parts configurable? I'm thinking that this could be useful when working with Storybook's stories, but then it doesn't seem to be sensible to support every possible project structure under the sun. Of course, a base of parts like test_, test., etc. is good, but this plugin could enable so much more with a little extra cost (unless it's hard to make plugins configurable, which I'm not knowledgeable about).

👋 @fatfisz: I think supporting configuration is a totally sensible approach, and it would indeed allow the extension to support a much larger set of projects. And it's certainly possible to make an extension configurable.

For this particular extension, I see the absence of configuration as a feature: I love that it just works for the [projects that I typically work on](https://github.com/jasonrudolph/significant-other-vscode/blob/fd3c9d6a705f2f7c03ee0da5666026f8e2c137c5/README.md?plain=1#L11). I like that I don't have to set it up for each project, and that I don't have any configuration that I have to maintain.

So at least for now, I want to stick with a zero-configuration approach. (This issue inspired me to [call that out in the README](https://github.com/jasonrudolph/significant-other-vscode/commit/fd3c9d6a705f2f7c03ee0da5666026f8e2c137c5).) I acknowledge that this means that the extension can't work for every project, but my current thinking is that the benefit of automatically working for lots of popular project structures is worth the tradeoff of not working for project structures that would need manual configuration.

With that in mind, I'm going to close this issue for now. Thanks for bringing this up! :bow:

**Comment by fatfisz** [comment]
I understand, thanks for the explanation!
