### ISSUE TITLE
dbt compiled view as an SO

### ISSUE THREAD

**Issue by shippy** [jasonrudolph/significant-other-vscode#4]
The [dbt project](https://github.com/dbt-labs/dbt-core) has a notion of compiled file for each templated SQL file under `models/`, `tests/` and `analysis/`.

For a file under `models/**/*.sql`, you'd expect a compiled file under `target/compiled/[project_name]/models/**/*.sql`. (There's also `target/compiled/[package]/models/**/*.sql`, but I believe name uniqueness is enforced across namespaces.

It would be great if the Significant Other toggle could work for this file constellation.

**Comment by jasonrudolph** [comment]
👋 @shippy: Thanks for sharing this idea. :bow: 

I'd like to keep this extension focused specifically on tests for now. I've discovered the hard way over the years that expanding the scope of an open source project can cause me to feel burnt out by the project over the long-term, so I'm gonna try to keep the scope narrow to avoid that.  I hope that makes sense.

Could you maybe use the code as a starting point for a new extension that provides the toggling that you described for the dbt project?
